---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:jakelawcheukwun/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: gcr.io/fit-sb-claw-devel/podinfo
      tag: dev-yfwk0a0k
    replicaCount: 1
    hpa:
      enabled: false
